spring.application.name=hortifruti

# Banco local
spring.datasource.url=jdbc:h2:file:./data/hortifruti
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# No Render, DATABASE_URL sobrescreve as configurações abaixo
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Porta local 8080 / Render usa PORT
server.port=${PORT:8080}

# Proteção simples, exclusivamente acadêmica
hortifruti.limpeza.senha=2340